/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function serialize(schema: Uint8Array, buffer: Uint8Array): string
export declare function deserialize(schema: Uint8Array, buffer: Uint8Array): Uint8Array
